export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POSTS_FAIL = 'LOAD_POSTS_FAIL'
export const LOAD_POST_BY_ID_SUCCESS = 'LOAD_POST_BY_ID_SUCCESS'
export const LOAD_POST_BY_ID_FAIL = 'LOAD_POST_BY_ID_FAIL'

